language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: xenial
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

    - os: linux
      dist: xenial
      r: release
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

  allow_failures:
    - os: linux
      dist: xenial
      r: devel
      

notifications:
  email:
    on_success: change
    on_failure: change